# Generated by Django 5.0.7 on 2024-07-31 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relation',
            old_name='create',
            new_name='created',
        ),
    ]
